//+------------------------------------------------------------------+
//| ScalperEA.mq5 - Aggressive Professional Scalper for MT5          |
//| Targets: EURUSD, XAUUSD                                          |
//| Timeframes: attach to M1 or M5 chart (or run two instances)      |
//| Author: Generated by GitHub Copilot persona                       |
//| NOTE: Trading forex/commodities carries risk. Backtest before use |
//+------------------------------------------------------------------+
#include <Trade/Trade.mqh>
#include <Trade\